#!/usr/bin/env python3
"""Pack game assets into an EPAK file for streaming via the ASSET_LOAD syscall.

Usage:
    python tools/pack_assets.py <manifest> <out_basepath>

Writes:
    <out_basepath>.pak          the packed asset file (ships next to the .rom on flash/SD)
    <out_basepath>_assets.txt   an include with one `var int ASSET_<NAME> = <id>;` per asset

Manifest format (whitespace-separated, '#' starts a comment). One asset per line:
    <name> <type> <width> <height> <source>
      type   : raw | sprite | tilemap | text | palette   (-> 0 | 1 | 2 | 3 | 4)
      width  : 0..255   (pixels for sprite, tiles for tilemap, 0 for raw/text)
      height : 0..255
      source : path to the asset's raw bytes, relative to the manifest's directory.
               'text' sources get a trailing NUL appended if they lack one.

EPAK layout (little-endian):
    0  4   magic "EPAK"
    4  1   version (=1)
    5  1   reserved
    6  2   asset_count
    8  12*N TOC entries: type(1) width(1) height(1) reserved(1) offset(4) length(4)
    ...    concatenated blob bytes
Asset id = TOC index.
"""
import os
import struct
import sys

TYPES = {"raw": 0, "sprite": 1, "tilemap": 2, "text": 3, "palette": 4}
MAGIC = b"EPAK"
VERSION = 1
HEADER_LEN = 8
TOC_ENTRY_LEN = 12


def parse_manifest(path):
    base_dir = os.path.dirname(os.path.abspath(path))
    entries = []  # (name, type_num, w, h, data)
    with open(path, encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 5:
                raise SystemExit(
                    f"{path}:{lineno}: expected '<name> <type> <w> <h> <source>'"
                )
            name, typ, w, h, src = parts
            if typ not in TYPES:
                raise SystemExit(f"{path}:{lineno}: unknown type '{typ}'")
            with open(os.path.join(base_dir, src), "rb") as sf:
                data = sf.read()
            if typ == "text" and (not data or data[-1] != 0):
                data += b"\x00"
            entries.append((name, TYPES[typ], int(w), int(h), data))
    return entries


def build_pack(entries):
    count = len(entries)
    base = HEADER_LEN + TOC_ENTRY_LEN * count
    toc = b""
    blobs = b""
    for (_name, t, w, h, data) in entries:
        offset = base + len(blobs)
        toc += struct.pack("<BBBBII", t, w & 0xFF, h & 0xFF, 0, offset, len(data))
        blobs += data
    return MAGIC + struct.pack("<BBH", VERSION, 0, count) + toc + blobs


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    manifest, outbase = sys.argv[1], sys.argv[2]
    entries = parse_manifest(manifest)
    pak = build_pack(entries)

    os.makedirs(os.path.dirname(os.path.abspath(outbase)), exist_ok=True)
    with open(outbase + ".pak", "wb") as f:
        f.write(pak)
    with open(outbase + "_assets.txt", "w", encoding="utf-8") as f:
        f.write("// Generated by tools/pack_assets.py - asset ids for this pack.\n")
        f.write("{\n")                               # a compilation unit must be brace-wrapped
        for i, entry in enumerate(entries):
            f.write(f"    const ASSET_{entry[0].upper()} = {i};\n")
        f.write("}\n")

    print(f"packed {len(entries)} asset(s) -> {outbase}.pak ({len(pak)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
