#!/usr/bin/env python3
"""Author a tilemap by PAINTING it: an indexed PNG where each PIXEL is one 16x16 tile.

Usage:
    python tools/pixel_map.py <map.png> <legend.txt> <out.gen.txt> [--name PREFIX]

The map PNG's width/height are the world's tile dimensions (1 pixel == 1 tile). Each pixel's palette
index is looked up in the legend to get a tile id (a PPU pattern slot) and whether it's solid.
Decorations (trees, rocks, ...) are just tiles too — paint them directly into the map like any other
terrain (the retro-console way: background tiles are always opaque, so bake each decoration's
surrounding ground color into its own tile art rather than relying on transparency).

Objects (player, enemies, NPCs, ...) are NOT part of this tool — place them with ordinary code
(hardcoded or computed coordinates), the same way you would without a map tool. This tool only
produces the tilemap + its collision flags.

Output is a brace-wrapped compilation unit the game `include`s:
    const MAP_W / MAP_H
    var byte world[MAP_W*MAP_H]      -- tile id per cell (row-major); doubles as the CPU collision map
    var byte tile_flags[N]           -- property byte per tile id (b0 solid), from the legend

Legend format (whitespace-separated, '#' comment). One palette index per line:
    <index> tile <tile_id> <solid 0|1>
Example:
    0 tile 16 0        # grass  (walkable)
    1 tile 17 1        # water  (solid)
    2 tile 18 0        # flowers
    3 tile 20 1        # tree   (solid; its own tile art, painted directly into the map)

STDLIB only (+ tools/png.py).
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import png  # noqa: E402


def parse_legend(path):
    """-> {index: (tile_id, solid)}."""
    tiles = {}
    with open(path, encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) != 4 or parts[1] != "tile":
                raise SystemExit(f"{path}:{lineno}: expected '<index> tile <tile_id> <solid 0|1>'")
            idx, _kw, tid, solid = parts
            tiles[int(idx, 0)] = (int(tid, 0), int(solid, 0))
    return tiles


def arr_lit(vals):
    return "{ " + ", ".join(str(v) for v in vals) + " }"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    name = ""
    for i, a in enumerate(sys.argv):
        if a == "--name" and i + 1 < len(sys.argv):
            name = sys.argv[i + 1] + "_"
    if len(args) != 3:
        print(__doc__)
        return 1
    png_path, legend_path, out_path = args

    img = png.read(png_path)
    tiles = parse_legend(legend_path)
    W, H = img.width, img.height

    world = bytearray(W * H)
    max_tile = 0
    for ty in range(H):
        for tx in range(W):
            idx = img.index_at(tx, ty)
            if idx not in tiles:
                raise SystemExit(f"{png_path}: palette index {idx} at ({tx},{ty}) is not in the legend")
            tid, _solid = tiles[idx]
            world[ty * W + tx] = tid
            max_tile = max(max_tile, tid)

    flags = [0] * (max_tile + 1)
    for (tid, solid) in tiles.values():
        if solid:
            flags[tid] |= 1

    lines = [
        "// Generated by tools/pixel_map.py -- paint a tilemap; include this in your game.",
        "{",
        f"    const {name}MAP_W = {W};",
        f"    const {name}MAP_H = {H};",
        f"    var byte {name}world[{W * H}] = {arr_lit(list(world))};",
        f"    var byte {name}tile_flags[{max_tile + 1}] = {arr_lit(flags)};",
        "}",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"pixel_map: {W}x{H} tiles -> {out_path}  (tile ids 0..{max_tile})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
